os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode9
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            HOMEBREW_NO_AUTO_UPDATE=1 brew install vapor/tap/vapor;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build
    - swift build -c release
    - swift test
    - if [ $TRAVIS_OS_NAME != "osx" ]; then
            sudo apt-get remove vapor;
            sudo apt-get install swift=3.1.1;
            swift build;
            swift build -c release;
            swift test;
        fi

after_success:
    - eval "$(curl -sL https://raw.githubusercontent.com/vapor-community/swift/master/codecov)"
